/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Place = {
  _id: string;
  _type: 'place';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  location: Geopoint;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  slug: Slug;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Place
  | SanityImageCrop
  | SanityImageHotspot
  | Geopoint
  | Slug
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: ../my-trips/src/sanity/queries/pages.ts
// Variable: PAGE_QUERY
// Query: *[    _type == "page" &&    slug.current == $slug  ][0] {    "id": _id,    heading,    "slug": slug.current,    body  }
export type PAGE_QUERY_RESULT = {
  id: string;
  heading: string;
  slug: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
} | null;

// Source: ../my-trips/src/sanity/queries/pages.ts
// Variable: PAGES_QUERY
// Query: *[    _type == "page" &&    defined(heading) &&    defined(slug.current)  ] | order(heading asc) {    "id": _id,    heading,    "slug": slug.current,    body  }
export type PAGES_QUERY_RESULT = Array<{
  id: string;
  heading: string;
  slug: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
}>;

// Source: ../my-trips/src/sanity/queries/pages.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[    _type == "page" &&    defined(slug.current)  ] | order(_updatedAt desc)[0...1] {    "slug": slug.current  }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../my-trips/src/sanity/queries/places.ts
// Variable: PLACE_QUERY
// Query: *[    _type == "place" &&    slug.current == $slug  ][0] {    "id": _id,    name,    "slug": slug.current,    description,    gallery[] {      "url": asset->url,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height    }  }
export type PLACE_QUERY_RESULT = {
  id: string;
  name: string;
  slug: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  gallery: Array<{
    url: string | null;
    width: number | null;
    height: number | null;
  }>;
} | null;

// Source: ../my-trips/src/sanity/queries/places.ts
// Variable: PLACES_QUERY
// Query: *[  _type == "place" &&  defined(name) &&  defined(slug.current) &&  defined(location.lat) &&  defined(location.lng)] | order(name asc) {  "id": _id,  name,  "slug": slug.current,  "location": {    "latitude": location.lat,    "longitude": location.lng  }}
export type PLACES_QUERY_RESULT = Array<{
  id: string;
  name: string;
  slug: string;
  location: {
    latitude: number | null;
    longitude: number | null;
  };
}>;

// Source: ../my-trips/src/sanity/queries/places.ts
// Variable: PLACE_SLUGS_QUERY
// Query: *[    _type == "place" &&    defined(slug.current)  ] | order(_updatedAt desc)[0...3] {    "slug": slug.current  }
export type PLACE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[\n    _type == "page" &&\n    slug.current == $slug\n  ][0] {\n    "id": _id,\n    heading,\n    "slug": slug.current,\n    body\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[\n    _type == "page" &&\n    defined(heading) &&\n    defined(slug.current)\n  ] | order(heading asc) {\n    "id": _id,\n    heading,\n    "slug": slug.current,\n    body\n  }\n': PAGES_QUERY_RESULT;
    '\n  *[\n    _type == "page" &&\n    defined(slug.current)\n  ] | order(_updatedAt desc)[0...1] {\n    "slug": slug.current\n  }\n': PAGE_SLUGS_QUERY_RESULT;
    '\n  *[\n    _type == "place" &&\n    slug.current == $slug\n  ][0] {\n    "id": _id,\n    name,\n    "slug": slug.current,\n    description,\n    gallery[] {\n      "url": asset->url,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height\n    }\n  }\n': PLACE_QUERY_RESULT;
    '*[\n  _type == "place" &&\n  defined(name) &&\n  defined(slug.current) &&\n  defined(location.lat) &&\n  defined(location.lng)\n] | order(name asc) {\n  "id": _id,\n  name,\n  "slug": slug.current,\n  "location": {\n    "latitude": location.lat,\n    "longitude": location.lng\n  }\n}': PLACES_QUERY_RESULT;
    '\n  *[\n    _type == "place" &&\n    defined(slug.current)\n  ] | order(_updatedAt desc)[0...3] {\n    "slug": slug.current\n  }\n': PLACE_SLUGS_QUERY_RESULT;
  }
}
